# Acknowledgments {-}


The authors wish to express their thanks to Christopher Gardner, Denise Gottfredson, Nguyen Phong, Katherine Stamps Mitchell, and all of their co-authors for generously sharing data from their research studies. A special thank you also is given to George Cobb who agreed to write the foreword. The authors are also indebted to the reviewers who provided invaluable feedback that helped improve this manuscript.

<br />

Thanks to my wife Lauren for endless support and to my dogs for forcing me to take the time to stop and scratch their bellies. A very special thank you goes to Joan Garfield, whose continued support and encouragement not only got me started on this journey but saw it through to the end. Thanks also to my family (Mom, Dad, and Sandra), friends (Tim, Heather, Tom, Sherri, Charles, and many other), and students (especially Jonathan, Chelsey, and Vimal) who put up with me during the last year. <br /> 
<span class="authorinitials">A.Z.</span>

Thanks to Joan, Adam, and Emma for continuing to be my inspiration.<br /> 
<span class="authorinitials">J.H.</span>

Thanks to Leslie for her patience and encouragement.<br /> 
<span class="authorinitials">J.L.</span>
