<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.361">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Statistical Modeling and Computation for Educational Scientists - 11&nbsp; Introduction to Multiple Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./03-02-understanding-statistical-control.html" rel="next">
<link href="./03-00-deeper-understanding.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

<link href="site_libs/pagedtable/css/pagedtable.css" rel="stylesheet">
<script src="site_libs/pagedtable/js/pagedtable.js"></script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="assets/sticky-notes.css">
<link rel="stylesheet" href="assets/table-styles.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./03-00-deeper-understanding.html">Deeper Understanding</a></li><li class="breadcrumb-item"><a href="./03-01-intro-to-multiple-regression.html"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Introduction to Multiple Regression</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistical Modeling and Computation for Educational Scientists</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Front Matter</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./01-00-statistical-computation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction to Statistical Computation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-01-r-and-rstudio-installation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">R and RStudio: Installation and Setup</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-02-getting-started-with-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Getting Started with R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-03-data-structures-in-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data Structures in R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-04-data-wrangling-with-dplyr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data Wrangling with dplyr</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-05-visualizing-with-ggplot2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Visualizing Data with ggplot2</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./02-00-regression-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Regression Basics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-01-simple-regression-description.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Simple Linear Regression—Description</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-02-ols-estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Ordinary Least Squares (OLS) Estimation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-03-correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Correlation and Standardized Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-04-coefficient-level-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Coefficient-Level Inference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-05-model-level-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Model-Level Inference</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./03-00-deeper-understanding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Deeper Understanding</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-01-intro-to-multiple-regression.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Introduction to Multiple Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-02-understanding-statistical-control.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Understanding Statistical Control</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-03-assumptions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Distributional Assumptions Underlying the Regression Model</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./04-00-extending-regression-model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Extending the Regression Model</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-01-dichotomous-predictors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Dichotomous Categorical Predictors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-02-polychotomous-predictors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Polychotomous Categorical Predictors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-03-interaction-effects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Introduction to Interaction Effects</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On This Page</h2>
   
  <ul>
  <li><a href="#observational-data-and-alternative-explanations" id="toc-observational-data-and-alternative-explanations" class="nav-link active" data-scroll-target="#observational-data-and-alternative-explanations"><span class="header-section-number">11.1</span> Observational Data and Alternative Explanations</a></li>
  <li><a href="#examining-the-seniority-predictor" id="toc-examining-the-seniority-predictor" class="nav-link" data-scroll-target="#examining-the-seniority-predictor"><span class="header-section-number">11.2</span> Examining the Seniority Predictor</a>
  <ul class="collapse">
  <li><a href="#simple-regression-model-seniority-as-a-predictor-of-income" id="toc-simple-regression-model-seniority-as-a-predictor-of-income" class="nav-link" data-scroll-target="#simple-regression-model-seniority-as-a-predictor-of-income"><span class="header-section-number">11.2.1</span> Simple Regression Model: Seniority as a Predictor of Income</a></li>
  </ul></li>
  <li><a href="#multiple-regression-model-education-level-and-seniority-as-a-predictors-of-income" id="toc-multiple-regression-model-education-level-and-seniority-as-a-predictors-of-income" class="nav-link" data-scroll-target="#multiple-regression-model-education-level-and-seniority-as-a-predictors-of-income"><span class="header-section-number">11.3</span> Multiple Regression Model: Education Level and Seniority as a Predictors of Income</a>
  <ul class="collapse">
  <li><a href="#model-level-results" id="toc-model-level-results" class="nav-link" data-scroll-target="#model-level-results"><span class="header-section-number">11.3.1</span> Model-Level Results</a></li>
  <li><a href="#coefficient-level-results" id="toc-coefficient-level-results" class="nav-link" data-scroll-target="#coefficient-level-results"><span class="header-section-number">11.3.2</span> Coefficient-Level Results</a></li>
  <li><a href="#coefficient-level-inference" id="toc-coefficient-level-inference" class="nav-link" data-scroll-target="#coefficient-level-inference"><span class="header-section-number">11.3.3</span> Coefficient-Level Inference</a></li>
  </ul></li>
  <li><a href="#multiple-regression-statistical-model" id="toc-multiple-regression-statistical-model" class="nav-link" data-scroll-target="#multiple-regression-statistical-model"><span class="header-section-number">11.4</span> Multiple Regression: Statistical Model</a></li>
  <li><a href="#anova-decomposition" id="toc-anova-decomposition" class="nav-link" data-scroll-target="#anova-decomposition"><span class="header-section-number">11.5</span> ANOVA Decomposition</a>
  <ul class="collapse">
  <li><a href="#hypotheses-tested-in-the-anova-output" id="toc-hypotheses-tested-in-the-anova-output" class="nav-link" data-scroll-target="#hypotheses-tested-in-the-anova-output"><span class="header-section-number">11.5.1</span> Hypotheses Tested in the ANOVA Output</a></li>
  <li><a href="#changing-the-order-of-the-predictors" id="toc-changing-the-order-of-the-predictors" class="nav-link" data-scroll-target="#changing-the-order-of-the-predictors"><span class="header-section-number">11.5.2</span> Changing the Order of the Predictors</a></li>
  </ul></li>
  <li><a href="#argh-which-set-of-results-should-i-use" id="toc-argh-which-set-of-results-should-i-use" class="nav-link" data-scroll-target="#argh-which-set-of-results-should-i-use"><span class="header-section-number">11.6</span> Argh! Which Set of Results Should I Use?</a></li>
  <li><a href="#presenting-results" id="toc-presenting-results" class="nav-link" data-scroll-target="#presenting-results"><span class="header-section-number">11.7</span> Presenting Results</a></li>
  <li><a href="#coefficient-plot" id="toc-coefficient-plot" class="nav-link" data-scroll-target="#coefficient-plot"><span class="header-section-number">11.8</span> Coefficient Plot</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="multreg" class="quarto-section-identifier"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Introduction to Multiple Regression</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>In this chapter, you will learn about including multiple predictors into the regression model. To do so, we will use the <a href="https://raw.githubusercontent.com/zief0002/modeling/main/data/riverview.csv">riverview.csv</a> data to examine whether education level is related to income. The data contain five attributes collected from a random sample of <span class="math inline">\(n=32\)</span> employees working for the city of Riverview, a hypothetical midwestern city (see the <a href="http://zief0002.github.io/epsy-8251/codebooks/riverview.html">data codebook</a>). To begin, we will load several libraries and import the data into an object called <code>city</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load libraries</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Import data</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>city <span class="ot">=</span> <span class="fu">read_csv</span>(<span class="at">file =</span> <span class="st">"https://raw.githubusercontent.com/zief0002/modeling/main/data/riverview.csv"</span>)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># View data</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>city</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["education"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["income"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["seniority"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["gender"],"name":[4],"type":["chr"],"align":["left"]},{"label":["party"],"name":[5],"type":["chr"],"align":["left"]}],"data":[{"1":"8","2":"26.430","3":"9","4":"female","5":"Independent"},{"1":"8","2":"37.449","3":"7","4":"Not female","5":"Democrat"},{"1":"10","2":"34.182","3":"16","4":"female","5":"Independent"},{"1":"10","2":"25.479","3":"1","4":"female","5":"Republican"},{"1":"10","2":"47.034","3":"14","4":"Not female","5":"Democrat"},{"1":"12","2":"46.488","3":"11","4":"female","5":"Democrat"},{"1":"12","2":"52.480","3":"16","4":"female","5":"Independent"},{"1":"12","2":"37.656","3":"14","4":"Not female","5":"Democrat"},{"1":"12","2":"50.265","3":"24","4":"Not female","5":"Democrat"},{"1":"14","2":"32.631","3":"5","4":"female","5":"Independent"},{"1":"14","2":"49.968","3":"18","4":"Not female","5":"Independent"},{"1":"14","2":"64.926","3":"26","4":"Not female","5":"Independent"},{"1":"15","2":"37.302","3":"8","4":"female","5":"Democrat"},{"1":"16","2":"38.586","3":"11","4":"female","5":"Independent"},{"1":"16","2":"55.878","3":"22","4":"female","5":"Independent"},{"1":"16","2":"59.499","3":"20","4":"female","5":"Independent"},{"1":"16","2":"55.782","3":"6","4":"Not female","5":"Democrat"},{"1":"16","2":"63.471","3":"10","4":"Not female","5":"Democrat"},{"1":"17","2":"60.068","3":"10","4":"female","5":"Independent"},{"1":"18","2":"54.840","3":"20","4":"female","5":"Republican"},{"1":"18","2":"62.466","3":"16","4":"female","5":"Republican"},{"1":"19","2":"56.019","3":"21","4":"female","5":"Independent"},{"1":"19","2":"65.142","3":"16","4":"Not female","5":"Republican"},{"1":"20","2":"56.343","3":"22","4":"female","5":"Independent"},{"1":"20","2":"54.672","3":"12","4":"female","5":"Independent"},{"1":"20","2":"61.629","3":"5","4":"Not female","5":"Republican"},{"1":"20","2":"82.726","3":"23","4":"Not female","5":"Republican"},{"1":"21","2":"71.202","3":"26","4":"female","5":"Democrat"},{"1":"21","2":"73.542","3":"16","4":"Not female","5":"Republican"},{"1":"22","2":"56.322","3":"8","4":"female","5":"Independent"},{"1":"22","2":"70.044","3":"14","4":"Not female","5":"Independent"},{"1":"24","2":"79.227","3":"27","4":"Not female","5":"Democrat"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p><br></p>
<section id="observational-data-and-alternative-explanations" class="level2" data-number="11.1">
<h2 data-number="11.1" class="anchored" data-anchor-id="observational-data-and-alternative-explanations"><span class="header-section-number">11.1</span> Observational Data and Alternative Explanations</h2>
<p>In a <a href="02-01-simple-regression-description.html">previous chapter</a>, we fitted a model regressing employees’ incomes on education level. We will do that again, but now we will also evaluate the inferential evidence around the effect of education on incomes.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit regression model</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>lm.a <span class="ot">=</span> <span class="fu">lm</span>(income <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> education, <span class="at">data =</span> city)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtain model-level results</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(lm.a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic      p.value    df logLik   AIC   BIC
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;        &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     0.632         0.619  8.98      51.5 0.0000000556     1  -115.  235.  240.
  deviance df.residual  nobs
     &lt;dbl&gt;       &lt;int&gt; &lt;int&gt;
1    2418.          30    32</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtain coefficient-level results</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(lm.a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["term"],"name":[1],"type":["chr"],"align":["left"]},{"label":["estimate"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["std.error"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["statistic"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["p.value"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"(Intercept)","2":"11.321379","3":"6.1232350","4":"1.848921","5":"0.07434601558004"},{"1":"education","2":"2.651297","3":"0.3696232","4":"7.172972","5":"0.00000005562116"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>The fitted equation,</p>
<p><span class="math display">\[
\hat{\mathrm{Income}_i} = 11.321 + 2.651(\mathrm{Education~Level}_i),
\]</span></p>
<p>suggests that the estimated mean income for employees with education levels that differ by one year varies by 2.651 thousand dollars, on average. We also found that differences in education level explained 63.2% of the variation in income, and that the empirical evidence is inconsistent with the hypothesis that education level explains none of the variation in incomes (<span class="math inline">\(p&lt;.001\)</span>). All this suggests that education level is likely related to income.</p>
<p>If the data had been collected as part of an experiment where we could have randomly assigned cases in our sample to the different levels of education (i.e., different values of <em>X</em>), the analysis would be done and we could conclude that education has a positive effect on income. Unfortunately, the data we used in the analysis is observational—we did not assign levels of the predictor to the cases in the sample. This means there could be other variables that are correlated with the predictor that are influencing the effect we saw in the data.</p>
<p>For example, we know that in civil service jobs, pay is influenced by seniority. So, one question is whether the distribution of seniority is similar across employees with different education levels. If not, it may be that those employees with higher education levels have higher levels of seniority. If that is the case, perhaps some (or all) of the positive effect of education on income that we observed is really just a function of higher seniority. To determine whether this is the case, we need to include seniority as another predictor in the model along with education level and see whether there is still an effect of education on income.</p>
<p><br></p>
</section>
<section id="examining-the-seniority-predictor" class="level2" data-number="11.2">
<h2 data-number="11.2" class="anchored" data-anchor-id="examining-the-seniority-predictor"><span class="header-section-number">11.2</span> Examining the Seniority Predictor</h2>
<p>Before we begin modeling, it behooves us to explore the seniority predictor. Below we examine the marginal distribution of seniority for the 32 employees in the sample.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine the marginal distribution</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> city, <span class="fu">aes</span>(<span class="at">x =</span> seniority)) <span class="sc">+</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_density</span>(<span class="at">geom =</span> <span class="st">"line"</span>) <span class="sc">+</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Seniority level (in years)"</span>) <span class="sc">+</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Probability density"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-density-seniority" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-01-intro-to-multiple-regression_files/figure-html/fig-density-seniority-1.png" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;11.1: Density plot of the marginal distribution of seniority.</figcaption>
</figure>
</div>
</div>
</div>
<p>We also compute numerical summaries of the distribution.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute mean and standard deviation</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>city <span class="sc">|&gt;</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">M =</span> <span class="fu">mean</span>(seniority),</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">SD =</span> <span class="fu">sd</span>(seniority)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["M"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["SD"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"14.8125","2":"6.948834"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>Seniority is symmetric with a typical employee having roughly 15 years of seniority. There is quite a lot of variation in seniority, with most employees having between 8 and 22 years of seniority.</p>
</blockquote>
<p>After we examine the marginal distribution, we should examine the relationships among all of the three variables we are considering in the analysis. Typically researchers will examine the scatterplot between each predictor and the outcome (to evaluate the functional forms of the relationships with the outcome) and also examine the correlation matrix. Since we have already looked at the scatterplot between education-level and income, we focus here on the relationship between seniority and income.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Relationship between income and seniority</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> city, <span class="fu">aes</span>(<span class="at">x =</span> seniority, <span class="at">y =</span> income)) <span class="sc">+</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Seniority (in years)"</span>) <span class="sc">+</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Income (in thousands of dollars)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-seniority-income" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-01-intro-to-multiple-regression_files/figure-html/fig-seniority-income-1.png" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;11.2: Scatterplot showing the relationship between seniority level and income.</figcaption>
</figure>
</div>
</div>
</div>
<p>The correlation matrix between all three variables is also examined.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Correlation matrix</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>city <span class="sc">|&gt;</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(income, education, seniority) <span class="sc">|&gt;</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">correlate</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["term"],"name":[1],"type":["chr"],"align":["left"]},{"label":["income"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["education"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["seniority"],"name":[4],"type":["dbl"],"align":["right"]}],"data":[{"1":"income","2":"NA","3":"0.7947847","4":"0.5819032"},{"1":"education","2":"0.7947847","3":"NA","4":"0.3394469"},{"1":"seniority","2":"0.5819032","3":"0.3394469","4":"NA"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>The relationship between seniority and income seems linear and positive (<span class="math inline">\(r=0.58\)</span>). This suggests that employees with more seniority also tend to have higher incomes. Education level and seniority are also modestly correlated (<span class="math inline">\(r=0.34\)</span>), indicating that employees with higher education levels tend to also have more seniority.</p>
</blockquote>
<p>Because there is a positive correlation between seniority and income in the sample, it suggests that city employees with more seniority level tend to have higher incomes. The correlation between the two predictors (education level and seniority) is also positive suggesting that city employees with higher education levels tend to have more seniority.</p>
<p><br></p>
<section id="simple-regression-model-seniority-as-a-predictor-of-income" class="level3" data-number="11.2.1">
<h3 data-number="11.2.1" class="anchored" data-anchor-id="simple-regression-model-seniority-as-a-predictor-of-income"><span class="header-section-number">11.2.1</span> Simple Regression Model: Seniority as a Predictor of Income</h3>
<p>It is also instructive to fit and examine the results from the simple regression model using seniority as a predictor of variation in income.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>lm.b <span class="ot">=</span> <span class="fu">lm</span>(income <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> seniority, <span class="at">data =</span> city)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Model-level results</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(lm.b)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic  p.value    df logLik   AIC   BIC
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     0.339         0.317  12.0      15.4 0.000477     1  -124.  254.  258.
  deviance df.residual  nobs
     &lt;dbl&gt;       &lt;int&gt; &lt;int&gt;
1    4342.          30    32</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Coefficient-level results</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(lm.b)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["term"],"name":[1],"type":["chr"],"align":["left"]},{"label":["estimate"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["std.error"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["statistic"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["p.value"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"(Intercept)","2":"35.690298","3":"5.0734526","4":"7.034716","5":"0.00000008074761"},{"1":"seniority","2":"1.218689","3":"0.3109638","4":"3.919070","5":"0.00047672958164"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>The fitted equation,</p>
<p><span class="math display">\[
\hat{\mathrm{Income}_i} = 35.690 + 1.219(\mathrm{Seniority~Level}_i)
\]</span></p>
<p>suggests that the estimated mean income for employees with seniority levels that differ by one year varies by 1.219 thousand dollars. We also find that differences in seniority level explain 33.9% of the variation in income, and that this empirical evidence is inconsistent with the hypothesis that seniority explains none of the variation in incomes (<span class="math inline">\(p&lt;.001\)</span>).</p>
<p>Our research question is focused on examining the relationship between education level and income. The relationships observed in this correlation matrix are consistent with the issues we were concerned about earlier, namely that the positive effect of education level on income may be due to the fact that employees with higher education levels have more seniority. And, the positive relationship between seniority and income is clouding the “real” underlying relationship between education and income.</p>
<p>What we need to know in order to determine the effect of education on incomes is whether <strong>after we account for any distributional differences in seniority across education level</strong> is there is still a relationship between education level and income. To answer this question, we will fit a model that includes both predictors.</p>
<p><br></p>
</section>
</section>
<section id="multiple-regression-model-education-level-and-seniority-as-a-predictors-of-income" class="level2" data-number="11.3">
<h2 data-number="11.3" class="anchored" data-anchor-id="multiple-regression-model-education-level-and-seniority-as-a-predictors-of-income"><span class="header-section-number">11.3</span> Multiple Regression Model: Education Level and Seniority as a Predictors of Income</h2>
<p>To fit the multiple regression model, we will just add (literally) additional predictors to the right-hand side of the <code>lm()</code> formula.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit multiple regression model</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>lm.c <span class="ot">=</span> <span class="fu">lm</span>(income <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> education <span class="sc">+</span> seniority, <span class="at">data =</span> city)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br></p>
<section id="model-level-results" class="level3" data-number="11.3.1">
<h3 data-number="11.3.1" class="anchored" data-anchor-id="model-level-results"><span class="header-section-number">11.3.1</span> Model-Level Results</h3>
<p>To interpret multiple regression results, begin with the model-level information.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Model-level results</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(lm.c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic       p.value    df logLik   AIC   BIC
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     0.742         0.724  7.65      41.7 0.00000000298     2  -109.  226.  232.
  deviance df.residual  nobs
     &lt;dbl&gt;       &lt;int&gt; &lt;int&gt;
1    1695.          29    32</code></pre>
</div>
</div>
<p>In a multiple regression model there are multiple predictors that are being used to explain variation in the outcome variable. We can begin by examining the <span class="math inline">\(R^2\)</span> value from the output. Interpreting this value, we say:</p>
<blockquote class="blockquote">
<p>Differences in education level AND seniority explain 74.2% of the variation in income, in the sample.</p>
</blockquote>
<p>The model-level test allows us to evaluate whether, together, these predictors explain variation in the outcome or whether any explained variation in the sample is attributable to sampling error. The formal model-level null hypothesis that tests this can be written mathematically as,</p>
<p><span class="math display">\[
H_0:\rho^2 = 0.
\]</span></p>
<p>This is a test of whether <em>all the predictors together</em> explain variation in the outcome variable. The results of this test, <span class="math inline">\(F(2,29)=41.65\)</span>, <span class="math inline">\(p&lt;.001\)</span>, suggest that the empirical evidence is inconsistent with the null hypothesis; it is likely that together education level and seniority level do explain variation in the population.</p>
<p>Equivalently, we can also write the model null hypothesis as a function of the predictor effects, namely,</p>
<p><span class="math display">\[
H_0:\beta_{\mathrm{Education~Level}} = \beta_{\mathrm{Seniority}} = 0.
\]</span></p>
<p>In plain English, this is akin to stating that there is NO EFFECT for every predictor included in the model. If the empirical data are inconsistent with this null hypothesis, it suggests that AT LEAST ONE of the predictor effects is likely not zero.</p>
<p>Although the two expressions of the model-level null hypothesis look quite different, they are answering the same question, namely whether the model predicts more variation in income than is attributable to sampling variation. Based on the results of the model-level hypothesis test we believe there is an effect of education-level on income, an effect of seniority on income, OR there is an effect of both predictors on income. The model-level results, however, do not allow us to determine which of the predictors has an effect on the outcome variable. For that we need to evaluate the coefficient-level results.</p>
<p><br></p>
</section>
<section id="coefficient-level-results" class="level3" data-number="11.3.2">
<h3 data-number="11.3.2" class="anchored" data-anchor-id="coefficient-level-results"><span class="header-section-number">11.3.2</span> Coefficient-Level Results</h3>
<p>Now we turn to the coefficient-level results produced in the <code>tidy()</code> output.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Coefficient-level results</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(lm.c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["term"],"name":[1],"type":["chr"],"align":["left"]},{"label":["estimate"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["std.error"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["statistic"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["p.value"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"(Intercept)","2":"6.7691720","3":"5.3728914","4":"1.259875","5":"0.2177593428983"},{"1":"education","2":"2.2518456","3":"0.3346443","4":"6.729073","5":"0.0000002202903"},{"1":"seniority","2":"0.7387965","3":"0.2100954","4":"3.516481","5":"0.0014597774256"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>First we will write the fitted multiple regression equation,</p>
<p><span class="math display">\[
\hat{\mathrm{Income}_i} = 6.769 + 2.252(\mathrm{Education~Level}_i) + .739(\mathrm{Seniority~Level}_i)
\]</span></p>
<p>The slopes (of which there are now more than one) are referred to as <em>partial regression slopes</em> or <em>partial effects</em>. They represent the effect of the predictor <em>AFTER</em> accounting for the effects of the other predictors included in the model. For example,</p>
<blockquote class="blockquote">
<ul>
<li>The <strong>partial effect of education level</strong> is 2.252. This indicates that a one year difference in education level is associated with a 2.252 thousand dollar difference in income (on average), after accounting for differences in seniority level.</li>
<li>The <strong>partial effect of seniority</strong> is 0.739. This indicates that a one year difference in seniority level is associated with a 0.739 thousand dollar difference in income (on average), after accounting for differences in education level.</li>
</ul>
</blockquote>
<div class="fyi">
<p>The language “after accounting for” is not ubiquitous in interpreting partial regression coefficients. Some researchers instead use “controlling for”, “holding constant”, or “partialling out the effects of”. For example, the education effect could also be interpreted these ways:</p>
<ul>
<li><p>A one year difference in education level is associated with a 2.252 thousand dollar difference in income (on average), <em>after controlling for differences</em> in seniority.</p></li>
<li><p>A one year difference in education level is associated with a 2.252 thousand dollar difference in income (on average), <em>after holding the effect</em> of seniority constant.</p></li>
<li><p>A one year difference in education level is associated with a 2.252 thousand dollar difference in income (on average), <em>after partialling out the effect</em> of seniority.</p></li>
</ul>
</div>
<p>Lastly, we can also interpret the intercept:</p>
<blockquote class="blockquote">
<p>The average income for all employees with 0 years of education AND 0 years of seniority is estimated to be 6.769 thousand dollars.</p>
</blockquote>
<p>This is the predicted average <em>Y</em> value when ALL the predictors have a value of 0. As such, it is often an extrapolated prediction and is not of interest to most applied researchers. For example, in our data, education level ranges from 8 to 24 years and seniority level ranges from 1 to 27 years. We have no data that has a zero value for either predictor, let alone for both. This makes prediction of the average <em>Y</em> value tenuous at these <em>X</em> values.</p>
<p><br></p>
</section>
<section id="coefficient-level-inference" class="level3" data-number="11.3.3">
<h3 data-number="11.3.3" class="anchored" data-anchor-id="coefficient-level-inference"><span class="header-section-number">11.3.3</span> Coefficient-Level Inference</h3>
<p>At the coefficient-level, the hypotheses being tested are about each individual predictor. The mathematical expression of the hypothesis is</p>
<p><span class="math display">\[
H_0: \beta_k = 0.
\]</span></p>
<p>In plain English, the statistical null hypothesis states: After accounting for ALL the other predictors included in the model, there is NO EFFECT of <em>X</em> on <em>Y</em>. These hypotheses are evaluated using a <em>t</em>-test. For example, consider the test associated with the education level coefficient.</p>
<p><span class="math display">\[
H_0: \beta_{\mathrm{Education~Level}} = 0
\]</span></p>
<p>This is akin to stating there is NO EFFECT of education level on income after accounting for differences in seniority level. The empirical evidence is inconsistent with this hypothesis, <span class="math inline">\(t(29)=6.73\)</span>, <span class="math inline">\(p&lt;.001\)</span>, suggesting that there is likely an effect of education on income after controlling for differences in seniority level. (Note that the <em>df</em> for the <em>t</em>-test for all of the coefficient tests is equivalent to the error, or denominator, <em>df</em> for the model-level <em>F</em>-test.)</p>
<p>It is important to note that the <em>p</em>-value at the model-level is different from any of the coefficient-level <em>p</em>-values. This is because when we include more than one predictor in a model, the hypotheses being tested at the model- and coefficient-levels are different. The model-level test is a simultaneous test of all the predictor effects, while the coefficient-level tests are testing the added effect of a particular predictor.</p>
<p><br></p>
</section>
</section>
<section id="multiple-regression-statistical-model" class="level2" data-number="11.4">
<h2 data-number="11.4" class="anchored" data-anchor-id="multiple-regression-statistical-model"><span class="header-section-number">11.4</span> Multiple Regression: Statistical Model</h2>
<p>The multiple regression model says that each case’s outcome (<em>Y</em>) is a function of two or more predictors (<span class="math inline">\(X_1\)</span>, <span class="math inline">\(X_2\)</span>, , <span class="math inline">\(X_k\)</span>) and some amount of error. Mathematically it can be written as</p>
<p><span class="math display">\[
Y_i = \beta_0 + \beta_1(X1_{i}) + \beta_2(X2_{i}) + \ldots + \beta_k(Xk_{i}) + \epsilon_i
\]</span></p>
<p>As with simple regression we are interested in estimating the values for each of the regression coefficients, namely, <span class="math inline">\(\beta_0\)</span>, <span class="math inline">\(\beta_1\)</span>, <span class="math inline">\(\beta_2\)</span>, …, <span class="math inline">\(\beta_k\)</span>. To do this, we again employ least squares estimation to minimize the sum of the squared error terms.</p>
<p>Since we have more than one <em>X</em> term in the fitted equation, the structural part of the model no longer mathematically defines a line. For example, the fitted equation from earlier,</p>
<p><span class="math display">\[
\hat{Y_i} = 6.769 + 2.252(X1_i) + 0.739(X2_i),
\]</span></p>
<p>mathematically defines a regression plane. (Note we have three dimensions, <em>Y</em>, <span class="math inline">\(X1\)</span>, and <span class="math inline">\(X2\)</span>. If we add predictors, we have four or more dimensions and we describe a hyperplane.)</p>
<p>The data and regression plane defined by the education level, seniority level, and income for the Riverview employees is shown below. The regression plane is tilted up in both the education level direction (corresponding to a positive partial slope of education) and in the seniority level direction (corresponding to a positive partial slope of seniority). The blue points are above the plane (employees with a positive residual) and the yellow points are below the plane (employees with a negative residual).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-scatter3d" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figs/03-01-3dscatterplot.png" class="img-fluid figure-img" style="width:60.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;11.3: Three-dimensional scatterplot showing the relationship between education level, seniority, and income. The fitted regression plane is also shown. Blue observations have a positive residual and yellow observations have a negative residual.</figcaption>
</figure>
</div>
</div>
</div>
<p>Graphically, the residuals from this model are the vertical distance between the observed points and the regression plane. Mathematically, they can be computed as,</p>
<p><span class="math display">\[
\hat{\epsilon_i} = Y_i - \hat{Y_i}
\]</span></p>
<p><br></p>
</section>
<section id="anova-decomposition" class="level2" data-number="11.5">
<h2 data-number="11.5" class="anchored" data-anchor-id="anova-decomposition"><span class="header-section-number">11.5</span> ANOVA Decomposition</h2>
<p>As with the simple regression model, we are interested in whether the model explains any of the unexplained variation identified in the baseline intercept-only model. As a reminder, we quantify the amount of unexplained variation through the residual sum of squares,</p>
<p><span class="math display">\[
\mathrm{SS}_{\mathrm{Residuals}} = \sum \hat{\epsilon_i}^2
\]</span></p>
<p>The residual sum of squares can be obtained using the <code>anova()</code> function.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtain ANOVA decomposition</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(lm.c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Df"],"name":[1],"type":["int"],"align":["right"]},{"label":["Sum Sq"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Mean Sq"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["F value"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["Pr(>F)"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"1","2":"4147.3305","3":"4147.33049","4":"70.94416","5":"0.000000002780644","_rn_":"education"},{"1":"1","2":"722.8836","3":"722.88365","4":"12.36564","5":"0.001459777425592","_rn_":"seniority"},{"1":"29","2":"1695.3133","3":"58.45908","4":"NA","5":"NA","_rn_":"Residuals"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>Here the <span class="math inline">\(\mathrm{SS}_{\mathrm{Residuals}} = 1695\)</span>. Because the model was fitted with OLS, any other plane defined with the predictors of education and seniority level; (i.e., different coefficient values for the intercept and predictors) would produce a higher sum of squared residuals value. Comparing the squared sum of residual from this model to that from the intercept-only model (<span class="math inline">\(\mathrm{SS}_{\mathrm{Residuals}} = 6566\)</span>), we find that there is less unexplained variation after including education and seniority level in the model. Here is the partitioning of the variation in income.</p>
<p><span class="math display">\[
\underbrace{6566}_{\substack{\text{Total} \\ \text{Variation}}} = \underbrace{4871}_{\substack{\text{Explained} \\ \text{Variation}}} + \underbrace{1695}_{\substack{\text{Unexplained} \\ \text{Variation}}}
\]</span></p>
<p>Dividing each term in the partitioning by the total sum of squares,</p>
<p><span class="math display">\[
\begin{split}
\frac{6566}{6566} &amp;= \frac{4871}{6566} + \frac{1695}{6566} \\[2ex]
1 &amp;= 0.742 + 0.258
\end{split}
\]</span></p>
<p>The proportion of variance explained by the model is the same as the <span class="math inline">\(R^2\)</span> value we obtained from the <code>glance()</code> function. We can also obtain the model sum of squares (4871) by adding the sum of squared term for the education predictor (4147) and that for the seniority predictor (723) from the <code>anova()</code> output. The total sum of squared (6566) can be computed by summing all the sum of squared terms in the <code>anova()</code> output:</p>
<p><span class="math display">\[
4147.3 + 722.9 + 1695.3 = 6565.5
\]</span></p>
<p>which is within rounding error of 6566.</p>
<p>Note that the output from <code>anova()</code> also partitions the <em>df</em> among the predictor terms and the residuals. Each predictor has 1 <em>df</em> associated with it, which gives the model 2 <em>df</em>. The residuals have 29 <em>df</em> associated with them. The model and residual <em>df</em> are the <em>df</em> used in the <em>F</em>-test and given in the <code>glance()</code> output. The total <em>df</em> in the data are <span class="math inline">\(2+29 = 31\)</span>, which is <span class="math inline">\(n-1\)</span>. Lastly, we point out that the residual <em>df</em> value from the <code>anova()</code> output (29) is the <em>df</em> associated with the <em>t</em>-tests for the coefficient-level tests (presented earlier).</p>
<p><br></p>
<section id="hypotheses-tested-in-the-anova-output" class="level3" data-number="11.5.1">
<h3 data-number="11.5.1" class="anchored" data-anchor-id="hypotheses-tested-in-the-anova-output"><span class="header-section-number">11.5.1</span> Hypotheses Tested in the ANOVA Output</h3>
<p>The <em>F</em>-values given in the <code>anova()</code> output do not match the <em>F</em>-test given in the <code>glance()</code> output. This is because the hypotheses being tested in the <code>anova()</code> output are different than that being tested in the <code>glance()</code> output. To understand the tests that are being performed, we need to understand how the variation is being partitioned in the model we fitted. The order the predictors in the <code>anova()</code> output (which is connected to the order they were included in the <code>lm()</code> function) shows this partitioning numerically. We can also create a diagram that shows this partitioning.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-anova-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figs/03-01-partitioning-1.png" class="img-fluid figure-img" style="width:60.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;11.4: Partitioning of variation associated with the model in which education-level is included prior to seniority-level.</figcaption>
</figure>
</div>
</div>
</div>
<p>In the diagram, the total unexplained variation is first explained by including education-level in the model (the first predictor included in the <code>lm()</code> function). This predictor explains some variation and leaves some of the variation unexplained. Then, seniority-level is allowed to explain any residual (unexplained) variation that remains.</p>
<p>The hypothesis that is being tested by an <em>F</em>-test is whether the explained variation is more than we expect because of sampling error. The way we quantify this is to compute <span class="math inline">\(R^2\)</span> which is a ratio of the explained variation to the total variation the predictor(s) is allowed to explain. The key here is that the numerator and denominator for <span class="math inline">\(R^2\)</span> are different depending on what is being tested.</p>
<p>Consider the <em>F</em>-test at the model-level from the <code>glance()</code> output. This is testing whether the model-level <span class="math inline">\(R^2\)</span> is more than we expect because of sampling error. In the diagram, the explained variation in the model-level <span class="math inline">\(R^2\)</span> is the total sum of all the blue circles since the model includes both education-level and seniority-level. The denominator is the baseline unexplained variation. Mathematically,</p>
<p><span class="math display">\[
\begin{split}
R^2_{\mathrm{Model}} &amp;= \frac{4147 + 723}{6566} \\[2ex]
&amp;= \frac{4879}{6566}
\end{split}
\]</span></p>
<p>This <em>F</em>-test examines whether this fraction (or proportion) is statistically different than 0. Here the results are those given in <code>glance()</code>, namely, <span class="math inline">\(F(2,29)=41.65\)</span>, <span class="math inline">\(p&lt;.001\)</span>.</p>
<p>In the <code>anova()</code> output, results from two different <em>F</em>-tests are presented. The <em>F</em>-test in the first line of this output is associated with the education-level predictor. This is testing whether education-level (by itself) explains variation in the outcome <em>given the model fitted</em>. In the diagram, the explained variation for the education-level <span class="math inline">\(R^2\)</span> is the blue circles associated with adding education to the model first. The denominator is the unexplained variation if we only consider the education and residual variation. Mathematically,</p>
<p><span class="math display">\[
\begin{split}
R^2_{\mathrm{Education\mbox{-}Level}} &amp;= \frac{4147}{4147 + 1695} \\[2ex]
&amp;= 0.710
\end{split}
\]</span></p>
<p>The <em>F</em>-test examines whether this fraction (or proportion) is statistically different than 0. Here the results are those given in the first line of the <code>anova()</code> output, namely, <span class="math inline">\(F(1,29)=70.94\)</span>, <span class="math inline">\(p&lt;.001\)</span>. The numerator <em>df</em> for the <em>F</em>-test is given in the <code>Df</code> column of the <code>anova()</code> output and the denominator <em>df</em> is the model’s residual <em>df</em>.</p>
<p>The <em>F</em>-test in the second line of this output is associated with the seniority-level predictor. This is testing whether seniority-level explains variation in the outcome AFTER education-level has already been allowed to explain any unexplained variation. In the diagram, the explained variation for the seniority-level <span class="math inline">\(R^2\)</span> is the blue circle associated with adding seniority-level to the model. The denominator is the unexplained variation that remains after education-level has explained all the variation it can (this is no longer the baseline unexplained variation). Mathematically,</p>
<p><span class="math display">\[
\begin{split}
R^2_{\mathrm{Seniority\mbox{-}Level} \vert \mathrm{Education\mbox{-}Level}} &amp;= \frac{723}{723 + 1695} \\[2ex]
&amp;= 0.299
\end{split}
\]</span></p>
<p>This <em>F</em>-test examines whether this fraction (or proportion) is statistically different than 0. Here the results are those given in the second line of the <code>anova()</code> output, namely, <span class="math inline">\(F(1,29)=12.37\)</span>, <span class="math inline">\(p=.001\)</span>.</p>
<p>This second test is asking whether there is an effect of seniority-level <em>after accounting for</em> education-level given the model fitted. This is equivalent to the hypothesis we tested for seniority-level in the coefficient-level output. In fact, the <em>p</em>-value from the <code>tidy()</code> output for the seniority-level effect is equivalent to the <em>p</em>-value associated with the seniority-level in the second line of the <code>anova()</code> output.</p>
<p><br></p>
</section>
<section id="changing-the-order-of-the-predictors" class="level3" data-number="11.5.2">
<h3 data-number="11.5.2" class="anchored" data-anchor-id="changing-the-order-of-the-predictors"><span class="header-section-number">11.5.2</span> Changing the Order of the Predictors</h3>
<p>Let’s re-fit the model, but this time we will include seniority-level in the model first and education-level second.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit model with different predictor order</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>lm.d <span class="ot">=</span> <span class="fu">lm</span>(income <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> seniority <span class="sc">+</span> education, <span class="at">data =</span> city)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="co"># ANOVA decomposition</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(lm.d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Df"],"name":[1],"type":["int"],"align":["right"]},{"label":["Sum Sq"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Mean Sq"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["F value"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["Pr(>F)"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"1","2":"2223.162","3":"2223.16221","4":"38.02937","5":"0.0000010089423","_rn_":"seniority"},{"1":"1","2":"2647.052","3":"2647.05193","4":"45.28042","5":"0.0000002202903","_rn_":"education"},{"1":"29","2":"1695.313","3":"58.45908","4":"NA","5":"NA","_rn_":"Residuals"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>Examining the ANOVA decomposition, we see that some of the values in the table are the same and others are different. To understand why, we will again compose the partitioning diagram.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-anova-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figs/03-01-partitioning-2.png" class="img-fluid figure-img" style="width:60.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;11.5: Partitioning of variation associated with the model in which seniority-level is included prior to education-level.</figcaption>
</figure>
</div>
</div>
</div>
<p>Consider the model-level <em>F</em>-test which tests whether the model-level <span class="math inline">\(R^2\)</span> is more than we expect because of sampling error. In the diagram, the explained variation in the model-level <span class="math inline">\(R^2\)</span> is the total sum of all the blue circles since the model includes both education-level and seniority-level. The denominator is the baseline unexplained variation. Mathematically,</p>
<p><span class="math display">\[
\begin{split}
R^2_{\mathrm{Model}} &amp;= \frac{2223 + 2647}{6566} \\[2ex]
&amp;= \frac{4879}{6566}
\end{split}
\]</span></p>
<p>This is the same model-level <span class="math inline">\(R^2\)</span> value we obtained earlier. Thus the results given in <code>glance()</code>, namely, <span class="math inline">\(F(2,29)=41.65\)</span>, <span class="math inline">\(p&lt;.001\)</span> are identical regardless of the order the predictors are included in the model.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Model-level output</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(lm.d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["r.squared"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["adj.r.squared"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["sigma"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["statistic"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["p.value"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["df"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["logLik"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["AIC"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["BIC"],"name":[9],"type":["dbl"],"align":["right"]},{"label":["deviance"],"name":[10],"type":["dbl"],"align":["right"]},{"label":["df.residual"],"name":[11],"type":["int"],"align":["right"]},{"label":["nobs"],"name":[12],"type":["int"],"align":["right"]}],"data":[{"1":"0.7417857","2":"0.7239778","3":"7.645854","4":"41.6549","5":"0.000000002976563","6":"2","7":"-108.9242","8":"225.8484","9":"231.7114","10":"1695.313","11":"29","12":"32"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>The <em>F</em>-test in the first line of this output is associated with the seniority-level predictor. This is testing whether seniority-level (by itself) explains variation in the outcome given the model. Mathematically,</p>
<p><span class="math display">\[
\begin{split}
R^2_{\mathrm{Seniority\mbox{-}Level}} =&amp; \frac{2223}{2223+1695} \\[2ex]
&amp;= 0.567
\end{split}
\]</span></p>
<p>The <em>F</em>-test examines whether this fraction (or proportion) is statistically different than 0. Here the results are those given in the first line of the <code>anova()</code> output, namely, <span class="math inline">\(F(1,29)=38.03\)</span>, <span class="math inline">\(p&lt;.001\)</span>.</p>
<p>The <em>F</em>-test in the second line of this output is testing whether education-level explains variation in the outcome AFTER seniority-level has already been allowed to explain any unexplained variation, given the model. Mathematically,</p>
<p><span class="math display">\[
\begin{split}
R^2_{\mathrm{Education\mbox{-}Level} \vert \mathrm{Seniority\mbox{-}Level}} &amp;= \frac{2647}{2647 + 1695} \\[2ex]
&amp;= 0.610
\end{split}
\]</span></p>
<p>The <em>F</em>-test examines whether this fraction (or proportion) is statistically different than 0. Here the results are those given in the second line of the <code>anova()</code> output, namely, <span class="math inline">\(F(1,29)=45.28\)</span>, <span class="math inline">\(p&lt;.001\)</span>. This test is asking whether there is an effect of education-level <em>after accounting for</em> seniority-level. The <em>p</em>-value from this test is equivalent to the <em>p</em>-value associated with the education-level effect in the <code>tidy()</code> output.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Coefficient-level output</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(lm.d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["term"],"name":[1],"type":["chr"],"align":["left"]},{"label":["estimate"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["std.error"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["statistic"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["p.value"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"(Intercept)","2":"6.7691720","3":"5.3728914","4":"1.259875","5":"0.2177593428983"},{"1":"seniority","2":"0.7387965","3":"0.2100954","4":"3.516481","5":"0.0014597774256"},{"1":"education","2":"2.2518456","3":"0.3346443","4":"6.729073","5":"0.0000002202903"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>Note that the output from <code>tidy()</code> is also the same, regardless of predictor order. This means that whichever order you include the predictors in the model, the tests of the partial effects (does a predictor explain variation AFTER all other predictors have already explained a much variation as they can) will be the same. Additionally, the fitted equation will be the same.</p>
<p><br></p>
</section>
</section>
<section id="argh-which-set-of-results-should-i-use" class="level2" data-number="11.6">
<h2 data-number="11.6" class="anchored" data-anchor-id="argh-which-set-of-results-should-i-use"><span class="header-section-number">11.6</span> Argh! Which Set of Results Should I Use?</h2>
<p>From all these different <em>F</em>-tests and <span class="math inline">\(R^2\)</span> values, we see that there are different ways of computing the amount of “variation accounted for” for any given predictor. The sum of squares for a particular predictor depends on whether we are considering it in isolation, or whether it is being considered in conjunction with other predictors. Not only that, but it also depends on the order that the predictor is included in the model! Similarly the amount of total unexplained variation depends on whether we consider all the unexplained variation in a variable, or whether we condition on a particular model.</p>
<p>In a regression analysis, we typically want to understand the amount of variation explained by a predictor after accounting for all the other predictors. That means, that when computing an <span class="math inline">\(R^2\)</span> value, the numerator will be based on the sum of squares if that predictor is last in the model. Similarly, the denominator will be based on the total variation available to explain after accounting for all the other predictors. To determine this, we include the predictor of interest last in the <code>lm()</code> and then examine the <code>anova()</code> output to obtain the sums of squares for the predictor and residuals. The <span class="math inline">\(R^2\)</span> value can then be computed based on those two values.</p>
<p>To evaluate whether that proportion of explained variation is more than we expect because of chance, we can evaluate the <em>p</em>-value for that predictor from the <code>tidy()</code> output. This is equivalent to asking: Is a particular predictor statistically important after controlling for the other predictors in the model? Again, this is the same <em>p</em>-value you get from the <code>anova()</code> output if the predictor is last in thr <code>lm()</code>.</p>
<div class="fyi">
<p>Some statisticians and quantitative methodologists have attempted to capture some of the differences in the various ways to compute “variance accounted for” by referring to different types of sums of squares. For example, the sums of squares in the <code>anova()</code> output is sometimes referred to as <em>Type 1 Sums of Squares</em> or <em>Sequential Sums of Squares</em>. While these terms can be helpful, they are not universally adopted and as a result often add more confusion than they solve. It is probably best to view them as different ways of partitioning and accounting for variation, and understand that how you decide to do this has an impact on how much variation a particular predictor explains and subsequently the <em>p</em>-value associated with it.</p>
</div>
<p><br></p>
</section>
<section id="presenting-results" class="level2" data-number="11.7">
<h2 data-number="11.7" class="anchored" data-anchor-id="presenting-results"><span class="header-section-number">11.7</span> Presenting Results</h2>
<p>It is quite common for researchers to present the results of their regression analyses in table form. Different models are typically presented in different columns and predictors are presented in rows. (Because it is generally of less substantive value, the intercept is often presented in the last row.)</p>
<p>Note that we <strong>DO NOT INCLUDE stars to indicate “statistical significance”</strong> as is the recommendation of the American Statistical Association. <span class="citation" data-cites="Wasserstein:2019">(<a href="#ref-Wasserstein:2019" role="doc-biblioref">Wasserstein &amp; Schirm, 2019</a>)</span></p>

<table class="table" style="width:70%; margin-left: auto; margin-right: auto;">
<caption>
Unstandardized coefficients (standard errors) for a taxonomy of OLS regression models to explain variation in Riverview city employee’s incomes. All models were fitted with <em>n</em>=32 observations.
</caption>
<thead>
<tr>
<th>
Predictor
</th>
<th>
Model A
</th>
<th>
Model B
</th>
<th>
Model C
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left">
Education level
</td>
<td style="text-align:center">
2.651<br>(0.370)
</td>
<td>
</td>
<td style="text-align:center">
2.252<br>(0.335)
</td>
</tr>
<tr>
<td style="text-align:left">
Seniority level
</td>
<td>
</td>
<td style="text-align:center">
1.219<br>(0.311)
</td>
<td style="text-align:center">
0.739<br>(0.210)
</td>
</tr>
<tr style="border-bottom: 1px solid black">
<td style="text-align:left">
Constant
</td>
<td style="text-align:center">
11.321<br>(6.123)
</td>
<td style="text-align:center">
35.690<br>(5.073)
</td>
<td style="text-align:center">
6.769<br>(5.373)
</td>
</tr>
<tr>
<td style="text-align:left">
R<sup>2</sup>
</td>
<td style="text-align:center">
0.632
</td>
<td style="text-align:center">
0.339
</td>
<td style="text-align:center">
0.742
</td>
</tr>
<tr>
<td style="text-align:left">
RMSE
</td>
<td style="text-align:center">
8.978
</td>
<td style="text-align:center">
12.031
</td>
<td style="text-align:center">
7.646
</td>
</tr>
</tbody>

</table>
<p>Based on the results of fitting the three models, we can now go back and answer our research questions. Do differences in education level explain variation in incomes? Based on Model A, the empirical evidence suggests the answer is yes. Is this true even after accounting for differences in seniority? The empirical evidence from Model C suggests that, again, the answer is yes. (Since it is not necessary for answering the RQ, some researchers might choose to not present the results from Model B.)</p>
<p><br></p>
</section>
<section id="coefficient-plot" class="level2" data-number="11.8">
<h2 data-number="11.8" class="anchored" data-anchor-id="coefficient-plot"><span class="header-section-number">11.8</span> Coefficient Plot</h2>
<p>To create a coefficient plot for a multiple regression, we will again use the <code>dwplot()</code> function from the <code>{dotwhisker}</code> package. To create coefficient plots for multiple models we need to create a data frame based on the <code>tidy()</code> output for each fitted model. We also need to append a column that identifies the model name in these data frames. Finally, we need to combine these data frames into a single data frame that we will use in the <code>dwplot()</code> function.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> Here we presented the coefficient plot for all three models. Another option would be to create this plot for only the “final” adopted model (e.g., Model C).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load library</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dotwhisker)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create tidy() data frames with model names</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>mod_1 <span class="ot">=</span> <span class="fu">tidy</span>(lm.a) <span class="sc">|&gt;</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">model =</span> <span class="st">"Model A"</span>)</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>mod_2 <span class="ot">=</span> <span class="fu">tidy</span>(lm.b) <span class="sc">|&gt;</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">model =</span> <span class="st">"Model B"</span>)</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>mod_3 <span class="ot">=</span> <span class="fu">tidy</span>(lm.c) <span class="sc">|&gt;</span></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">model =</span> <span class="st">"Model C"</span>)</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine into single data frame</span></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>all_models <span class="ot">=</span> <span class="fu">rbind</span>(mod_1, mod_2, mod_3)</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Create plot</span></span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a><span class="fu">dwplot</span>(all_models, <span class="at">show_intercept =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">name =</span> <span class="st">"Model"</span>, <span class="at">values =</span> <span class="fu">c</span>(<span class="st">"#c62f4b"</span>, <span class="st">"#c62f4b"</span>, <span class="st">"#c62f4b"</span>)) <span class="sc">+</span></span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">name =</span> <span class="st">"Estimate"</span>) <span class="sc">+</span></span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_discrete</span>(<span class="at">name =</span> <span class="st">"Coefficients"</span>, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Seniority"</span>, <span class="st">"Education"</span>)) <span class="sc">+</span></span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>model) <span class="sc">+</span></span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">color =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-coefplot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-01-intro-to-multiple-regression_files/figure-html/fig-coefplot-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;11.6: Coefficient plot for the model regressing income on education. Uncertainty is displayed based on the 95% confidence intervals.</figcaption>
</figure>
</div>
</div>
</div>
<p>This plot shows graphically what we observed in the numerical results. There does seem to be a positive effect of education-level on employee income. After including seniority-level in the model, the effect of education-level is somewhat tempered, but it is still positive. There is, however, some uncertainty in the exact magnitude of the size of the effect as is shown in the wide 95% confidence interval for education-level in the plot.</p>
<p><br></p>


<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-Wasserstein:2019" class="csl-entry" role="listitem">
Wasserstein, R., &amp; Schirm, A. (2019). <em>Moving to a world beyond <span class="math inline">\(p &lt; .05\)</span></em>. Keynote presentation at the <span>U</span>nited <span>S</span>tates <span>C</span>onference on <span>T</span>eaching <span>S</span>tatistics.
</div>
</div>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>It is critical when you are changing labels on the axes that you double-check the actual <code>tidy()</code> output so that you don’t erroneously mislabel the coefficients. Here for example, the <code>tidy()</code> output indicates that in Model C the coefficient for education level is 2.25 and the seniority coefficient is 0.739. This corresponds to what we see in the plot.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./03-00-deeper-understanding.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Deeper Understanding</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./03-02-understanding-statistical-control.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Understanding Statistical Control</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>